before_script: 
  - cd code/travelapp-boot/
  - echo $TRAVIS_BUILD_DIR
  - echo "Sai "

cache:
  directories:
    - $HOME/.m2
    
script:
  - echo $TRAVIS_BUILD_DIR
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mkdir $TRAVIS_BUILD_DIR/build
  - cp target/travelapp-0.0.1-SNAPSHOT.jar $TRAVIS_BUILD_DIR/build/travelapp.jar  
